# ============================================
# SECRET - Datos SENSIBLES
# ============================================
apiVersion: v1
kind: Secret
metadata:
  name: catalogs-service-secret
  namespace: catalogs-service
  labels:
    app: catalogs-service

type: Opaque

# stringData convierte automáticamente a base64
stringData:
  DB_USERNAME: "postgres"
  DB_PASSWORD: "postgres"
